services:
  auth-service:
    container_name: auth
    build:
      context: ./microservice-auth
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ACTIVE_PROFILE:
      AMQP_URL:
      PG_USER: ${PG_AUTH_USER}
      PG_PASSWORD: ${PG_AUTH_PASSWORD}
      PG_DB: ${PG_AUTH_DB}
      PG_URL: jdbc:postgresql://auth_db:5432/${PG_DB}
    depends_on:
      - auth_db
      - rabbitmq

  users-service:
    container_name: users
    build:
      context: ./microservice-users
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      ACTIVE_PROFILE:
      AMQP_URL:
      PG_USER: ${PG_USERS_USER}
      PG_PASSWORD: ${PG_USERS_PASSWORD}
      PG_DB: ${PG_USERS_DB}
      PG_URL: jdbc:postgresql://users_db:5433/${PG_DB}
    depends_on:
      - users_db
      - rabbitmq

  auth_db:
    container_name: auth_db
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${PG_AUTH_USER}
      POSTGRES_PASSWORD: ${PG_AUTH_PASSWORD}
      POSTGRES_DB: ${PG_AUTH_DB}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  users_db:
    container_name: users_db
    image: postgres:17-alpine
    command: -p 5433
    environment:
      POSTGRES_USER: ${PG_USERS_USER}
      POSTGRES_PASSWORD: ${PG_USERS_PASSWORD}
      POSTGRES_DB: ${PG_USERS_DB}
    env_file:
      - .env
    ports:
      - "5433:5433"
    volumes:
      - users_db_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    hostname: rabbitmq-local
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  auth_db_data:
  users_db_data:
  rabbitmq_data: