spring:
  profiles:
    active: ${ACTIVE_PROFILE:test}

  application:
    name: auth

  amqp:
    deserialization:
      trust:
        all: true

broker:
  queues:
    userCreated:
      name: user_credentials_created
    userUpdated:
      name: user_credentials_updated
