spring:
  profiles:
    active: ${ACTIVE_PROFILE:test}

  application:
    name: auth

  amqp:
    deserialization:
      trust:
        all: true

broker:
  exchanges:
    userCreated:
      name: user.created.fanout
    userUpdated:
      name: user.updated.fanout