server:
  port: 8081

spring:
  application:
    name: user

  profiles:
    active: ${ACTIVE_PROFILE:test}

  amqp:
    deserialization:
      trust:
        all: true

broker:
  queues:
    userCreated:
      name: user_credentials_created
    userUpdated:
      name: user_credentials_updated



