server:
  port: 8081

spring:
  application:
    name: user

  profiles:
    active: ${ACTIVE_PROFILE:test}

  amqp:
    deserialization:
      trust:
        all: true

broker:
  exchanges:
    userCreated:
      name: user.created.fanout
    userUpdated:
      name: user.updated.fanout

  queues:
    createUser:
      name: create_user_profile
    updateUser:
      name: update_user_profile